#! /bin/bash

set -e

cp hooks/pre-commit .git/hooks/pre-commit

GPG="gpg --yes --local-user craig@barkingiguana.com --armor"

find 20?? -name "*.asc" -delete
find _posts -type f -name "*.md" -or -name "*.html" | sort | sed 's/_posts\///' | while read FILE; do
  echo "Signing $FILE"
  DIR=$(echo ${FILE:0:10} |sed 's/-/\//' |sed 's/-/\//')
  test -d $DIR || mkdir -p $DIR
  TARGET="${FILE:11}.orig"
  perl -ne '$i > 1 ? print : /^---/ && $i++' _posts/$FILE > $DIR/$TARGET
  $GPG --output $DIR/$TARGET.asc --detach-sig $DIR/$TARGET
done

$GPG --output verification.md.asc --detach-sig verification.md
